{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccount.roleName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "odd-tracing-gateway.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.serviceAccount.roleName }}
subjects:
  - kind: ServiceAccount
    name: {{ include "odd-tracing-gateway.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}