apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odd-collector.fullname" . }}
  labels:
    {{- include "odd-collector.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.passwordSecretsEnvs }}
  {{ $k | quote }}: {{ $v | toString | b64enc | quote }}
  {{- end }}