apiVersion: v1
kind: Service
metadata:
  name: {{ include "odd-collector.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 6 }}
  {{- end }}
  labels:
    {{- include "odd-collector.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "odd-collector.selectorLabels" . | nindent 4 }}
