apiVersion: v1
kind: Service
metadata:
  name: {{ include "odd-adapter.fullname" . }}
  labels:
    {{- include "odd-adapter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "odd-adapter.selectorLabels" . | nindent 4 }}
