apiVersion: v1
kind: Service
metadata:
  name: {{ include "odd-platform.fullname" . }}
  annotations:
    "service.beta.kubernetes.io/load-balancer-source-ranges": "{{ .Values.global.loadBalancerSourceRanges }}"
  labels:
    {{- include "odd-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.global.platformServiceType }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "odd-platform.selectorLabels" . | nindent 4 }}
